<img style="float: right; margin: 0px 0px 15px 15px;" src="https://ceppe.org.mx/wp-content/uploads/2015/11/Logo_Horizontal_ITESO.jpg" width="400px" height="200px" />
            
          
# Tarea 1

**Estudiante 1:** Berlin Isabel Preciado Escalera-723259

**Estudiante 2:** Mateo Venea

**Profesor:** Oscar David Jaramillo Zuluaga

**Fecha:** 31 de agosto 2021



## INSTRUCCIONES



Este archivo contiene las pautas necesarias para crear el archivo conjunto en Github, usando los notebooks de Jupyter:

1.  El archivo debe realizarse en parejas y sólo uno de los dos debe crear en su cuenta de *Github* un repositorio con el nombre **ProyectoConjunto\_APELLIDO1\_APELLIDO2**. A la persona que creó el repositorio la llamaremos (ESTUDIANTE 1 ). El APELLIDO se debe de escribir (Iniciales del nombre y primer apellido), por ejemplo si yo creara el archivo lo debería de nombrar *ProyectoConjunto\_ODJaramillo*. 
1.  Posteriormente, desde la cuenta del (ESTUDIANTE 2), 'aquel que no creó el repositorio anterior', ingresar al perfil del ESTUDIANTE 1 y en el repositorio creado en el paso 1, realizar un "fork" de este repositorio en su perfil, y además realizar los pasos en Gitkraken para hacer dicho repositorio "Remoto (REMOTE)" VER DICHO PROCEDIMIENTO EN LA CLASE **Clase2_GitTurorial2**.
1.  Luego de realizados los pasos 1 y 2, el ESTUDIANTE 1 y ESTUDIANTE 2, desde su computador realizar un *clone* del repositorio creado en el numeral 1 en la carpeta que cada quién haya asignado para el curso en su computador. 
1.  Luego desde Jupyter el ESTUDIANTE 1, crea un nuevo ``notebook`` en el repositorio del paso 3. 
1.  En este nuevo notebook el ESTUDIANTE 1 y ESTUDIANTE 2, deben realizar una presentación describiendo sus expectativas del curso y la transcipción de la Figura 1 y Figura 2 respectivamente, haciendo uso de la sintaxis Markdown. Recuerden definir unas celdas donde cada usuario modificará el cuaderno de python para evitar futuros conflictos. 

**RECOMENDACIÓN:ANTES DE EMPEZAR A REALIZAR MUCHAS MODIFICACIONES DEL NOTEBOOK PRIMERO REALICEN CAMBIOS PEQUEÑOS EN EL ARCHIVO EN CONJUNTO Y VERIFIQUEN SI TANTO EL ``ESTUDIANTE 1`` COMO EL ``ESTUDIANTE 2``  RECIBEN LAS ACTUALIZACIONES QUE REALIZAN CADA UNO EN EL PROYECTO PARA VERIFICAR QUE EL REMOTE ESTUVO BIEN CONFIGURADO.**
>Les recomiendo ver los siguientes enlaces para ver distintas funciones para escribir en markdown.
>    - [Creador de tablas online](https://www.tablesgenerator.com/markdown_tables)
>    - [Sintáxis markdown](https://joplinapp.org/markdown/)

6. Cuando ya se encuentre el proyecto conjunto con la información del ESTUDIANTE 1 y ESTUDIANTE 2, el ``ESTUDIANTE 2``  debe de realizar un `pull request` con las modificaciones realizadas a el `ESTUDIANTE 1` para que este realice un merge a la rama `master`, con las moficaciones propuestas por el `ESTUDIANTE 2`, TAL Y CÓMO SE REALIZÓ EN CLASE. (Recuerden que los pull request se generan en *Gitkraken* y se administran los comentarios o cambios propuestos por su compañero desde *Github* ver `Clase1_GitTurorial` para aclaración de dudas, donde se explica cómo crear *branch y pull request*)

# Estudiante 1

### **Expectativas del curso**
En base a los comentarios de algúnos de mis compañeros, creo que en esta materia reafirmaré conocimientos ya vistos en materias pasadas donde he usado el lenguaje de python, además poder tener una mejor habilidad lógica y poder tener agilidez al programar, así como  aprender a utilizar herramientas que me ayuden a simular distintos escenarios financieros y sus impactos para poder crear expectativas o anticiparme a cambios en el mercado y así ayudar a cualquier lugar en el que me encuentre trabajando.


|$i$|$x$|$f(x)$|
|------|------|------|
|$0$ |$-1$|$0.3678$|
|$\color{red}{1}$|$\color{red}{-0.5}$|$\color{red}{0.7788}$|
|$\color{blue}{2}$|$\color{blue}{0}$|$\color{blue}{1}$|
|$\color{red}{3}$|$\color{red}{0.5}$|$\color{red}{0.7788}$|
|$4$|$1$|$0.3678$|

$$\text{Cuadro 1: Tabla de valores de 𝑓(𝑥)}$$

$$\begin{equation}
\int_{-1}^{1} e^{-x^{2}}dx\approx\frac{0,5}{3}\left [f(-1)+f(1)+4(\color{red}{f(-0,5)+f(0,5)})+2\color{blue}{f(0)}\right]
\end{equation}$$
$$\begin{equation}
\approx \frac{0,5}{3}[0,3678 + 0,3678 + 4 (\color{red}{0,7788 + 0,7788}) + 2 \cdot \color{blue}{1})] \approx 1,4943
\end{equation}$$

$$\text{ A modo de verificación, se calculará por software, el valor del área para n = 100, un valor mucho más elevado al que se utilizó anteriormente.}$$
$\text{Si lo calculado previamente es correcto, se esperaría que sea próximo al valor presentado a continuación para ser una buena aproximación.}$

$$\begin{align}
\int_{-1}^1 e^{-x^2}dx \approx 1,4936
\end{align}$$

In [21]:
import numpy as np
f = [0, 1]
for i in range(2, 100):
    f.append(f[i - 1] + f[i - 2])
print(np.reshape(np.array(f), (10, 10)))

[[0 1 1 2 3 5 8 13 21 34]
 [55 89 144 233 377 610 987 1597 2584 4181]
 [6765 10946 17711 28657 46368 75025 121393 196418 317811 514229]
 [832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817
  39088169 63245986]
 [102334155 165580141 267914296 433494437 701408733 1134903170 1836311903
  2971215073 4807526976 7778742049]
 [12586269025 20365011074 32951280099 53316291173 86267571272
  139583862445 225851433717 365435296162 591286729879 956722026041]
 [1548008755920 2504730781961 4052739537881 6557470319842 10610209857723
  17167680177565 27777890035288 44945570212853 72723460248141
  117669030460994]
 [190392490709135 308061521170129 498454011879264 806515533049393
  1304969544928657 2111485077978050 3416454622906707 5527939700884757
  8944394323791464 14472334024676221]
 [23416728348467685 37889062373143906 61305790721611591 99194853094755497
  160500643816367088 259695496911122585 420196140727489673
  679891637638612258 1100087778366101931 1779979416004714189]
 [28800671943